version: "3.8"

services:
  nginx-1:
    container_name: "nginx-alias1"
    image: "seffeng/openresty"
    ports:
      - "80:80"
      - "443:443"
    networks:
      network-01:
        aliases:
          - nginx-net1
    volumes:
      - "/opt/websrv/data/wwwroot:/opt/websrv/data/wwwroot"
      - "/opt/websrv/tmp:/opt/websrv/tmp"
      - "/opt/websrv/logs/nginx:/opt/websrv/logs"
      - "/opt/websrv/config/nginx/conf.d:/opt/websrv/config/nginx/conf.d"
      - "/opt/websrv/config/nginx/certs.d:/opt/websrv/config/nginx/certs.d"

networks:
  network-01:
    driver: bridge
    name: network-01